"use client";
import { BatteryCharging, CheckCheck, Clock3, Info, MapPin, Timer } from "lucide-react";
import { previewProviderName } from "@/features/household-profile/provider-preview";
import { cachedAge, countdownParts, durationLabel, manilaTimestamp, preparationItems, scheduleState } from "../calculations";
import type { BrownoutPreviewPlan, PreparationId } from "../types";

export default function ReadinessPanel({ plan, now, stale, disabled, onToggle }: { plan: BrownoutPreviewPlan; now: number; stale: boolean; disabled: boolean; onToggle: (id: PreparationId) => void }) {
  const { details, match, original } = plan.advisory, schedule = scheduleState(details, now), parts = schedule.remaining !== null ? countdownParts(schedule.remaining) : null;
  return <div className="bready-workspace"><section className="bready-schedule ui-panel" aria-label="Saved published schedule">
    <div className="bready-section-head"><span><Timer aria-hidden="true" /></span><div><p>{original.kind === "sample" ? "Sample plan · fictional announcement" : "Saved preparation plan"}</p><h2>{details.title || "Published interruption schedule"}</h2></div></div>
    <p className="bready-location"><MapPin size={16} aria-hidden="true" /><span>{match.householdBasis.location || "Household location incomplete"}<small>{previewProviderName(match.householdBasis.provider)} · household basis saved with this plan</small></span></p>
    <div className={`bready-countdown ${stale ? "is-stale" : ""}`}>
      <p>{stale ? "Previous reviewed schedule · review changes below" : "Countdown to published start"}</p>
      {parts ? <><div className="bready-clock" aria-label={`${parts.days} days ${parts.hours} hours ${parts.minutes} minutes ${parts.seconds} seconds to published start`}>{(["days", "hours", "minutes", "seconds"] as const).map(unit => <span key={unit}><b>{String(parts[unit]).padStart(2, "0")}</b><small>{unit}</small></span>)}</div><span className="bready-state">{stale ? "Previous schedule" : "Scheduled ahead"}</span></> : <><h3>{schedule.state === "elapsed" ? "Schedule elapsed" : schedule.state === "started" ? "Published start has passed" : "Start time unknown"}</h3><p>{schedule.state === "elapsed" ? "The published window has ended. Actual power and restoration status are unconfirmed." : schedule.state === "started" ? "The device clock has reached the published start. An actual interruption is unconfirmed." : "No countdown is available. Review a complete start date and time when your provider publishes them."}</p></>}
    </div>
    <dl className="bready-schedule-fields"><div><dt>Published start</dt><dd>{schedule.start !== null ? manilaTimestamp(schedule.start) : "Unknown"}</dd></div><div><dt>Published end</dt><dd>{schedule.end !== null ? manilaTimestamp(schedule.end) : "Unknown"}</dd></div><div><dt>Scheduled duration</dt><dd>{durationLabel(schedule.duration)}</dd></div><div><dt>Expected restoration as stated</dt><dd>{details.expectedRestoration || "Unknown · not provided"}</dd></div></dl>
    <p className="bready-clock-note"><Clock3 size={15} aria-hidden="true" />Asia/Manila (UTC+08:00) · uses your device clock. A published end is not a restoration confirmation.</p>
    <p className="bready-muted">{cachedAge(plan.advisory.reviewedAt, now)} · saved {manilaTimestamp(plan.updatedAt)} Asia/Manila.</p>
  </section><section className="bready-checklist ui-panel" aria-label="Preparation checklist"><div className="bready-section-head"><span><BatteryCharging aria-hidden="true" /></span><div><p>Your household preparation</p><h2>Small steps, ready essentials</h2></div></div><div className="bready-progress"><span>{plan.checked.length} of {preparationItems.length} checked</span><progress value={plan.checked.length} max={preparationItems.length} aria-label="Checklist completion" /></div><ul>{preparationItems.map(item => <li key={item.id} className={plan.checked.includes(item.id) ? "is-checked" : ""}><label><input type="checkbox" checked={plan.checked.includes(item.id)} disabled={disabled} onChange={() => onToggle(item.id)} /><span><strong>{item.title}</strong><small>{item.detail}</small></span></label></li>)}</ul>{plan.checked.length === preparationItems.length && <p className="bready-complete" role="status"><CheckCheck size={18} aria-hidden="true" />All preparation items checked by you.</p>}<p className="bready-muted"><Info size={14} aria-hidden="true" />Checklist progress is saved in this browser. It does not confirm power status or send reminders.</p></section></div>;
}
