"use client";
import { useEffect, useRef, useState, type KeyboardEvent } from "react";
import Image from "next/image";
import Link from "next/link";
import { CalendarDays, ChevronRight, CircleAlert, CircleCheck, Clock3, Info, MapPin, Megaphone, Plus, Save, Sparkles, WifiOff, Wrench, X } from "lucide-react";
import AppHeader from "@/features/dashboard/components/AppHeader";
import AppNavigation from "@/features/dashboard/components/AppNavigation";
import { usePreviewHousehold } from "@/features/dashboard/use-preview-household";
import { previewProviderName } from "@/features/household-profile/provider-preview";
import { advisoryTypeLabels, formatAdvisoryDate, type AdvisoryFilter, type AdvisoryTab } from "../advisory-preview";
import { advisoryTab, captureMatch, matchIsStale, matchLabels, matchPreviewAdvisory, sampleAdvisory, sampleMatchHousehold, scheduleLabel, sourceLink } from "../review-preview";
import { usePreviewAdvisories } from "../use-preview-advisories";
import { usePreparationProgress } from "../use-preparation-progress";
import { advisoryPreparationItems, preparationEligible, preparationKey as keyForPreparation, type AdvisoryPreparationId } from "../preparation-progress";
import type { AdvisorySample, ReviewedAdvisory } from "../types";
import AdvisoryOriginalView from "./advisory-original";
import LocationMatchPreview from "./location-match-preview";
import { AdvisoryPreparationChecklist, AdvisoryPreparationComplete } from "./advisory-preparation";

const icons = { scheduled: Megaphone, unscheduled: CircleAlert, notice: Info, restored: CircleCheck };
const filters: { value: AdvisoryFilter; label: string }[] = [{ value: "all", label: "All" }, { value: "scheduled", label: "Scheduled" }, { value: "unscheduled", label: "Unscheduled" }, { value: "notice", label: "Notice" }, { value: "restored", label: "Restoration updates" }];
const dateLabel = (date: string) => date ? formatAdvisoryDate(date) : "Date unknown";
const timestamp = (value: string) => new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Manila" }).format(new Date(value));

export default function AdvisoriesScreen() {
  const { household, ready: householdReady } = usePreviewHousehold(), saved = usePreviewAdvisories(), progress = usePreparationProgress();
  const [tab, setTab] = useState<AdvisoryTab>("active"), [filter, setFilter] = useState<AdvisoryFilter>("all"), [gallery, setGallery] = useState(false), [examples, setExamples] = useState<ReviewedAdvisory[]>([]);
  const [selection, setSelection] = useState<{ id: string; gallery: boolean } | null>(null), [deleting, setDeleting] = useState(false), [message, setMessage] = useState(""), [offline, setOffline] = useState(false);
  const [completionKey, setCompletionKey] = useState<string | null>(null);
  const dialog = useRef<HTMLDialogElement>(null), trigger = useRef<HTMLButtonElement | null>(null), queryRead = useRef(false), checklistRequested = useRef(false), tabs = useRef<Partial<Record<AdvisoryTab, HTMLButtonElement | null>>>({});
  const galleryRecords = examples.map(record => progress.sample?.record.id === record.id ? progress.sample.record : record);
  const ready = householdReady && saved.ready && progress.ready, basis = gallery ? sampleMatchHousehold : household, records = gallery ? galleryRecords : saved.records;
  const selected = selection ? (selection.gallery ? galleryRecords : saved.records).find(record => record.id === selection.id) : undefined;
  const selectedBasis = selection?.gallery ? sampleMatchHousehold : household;
  const preparationKey = selected ? keyForPreparation(selected, selectedBasis) : "";
  const checked = selection?.gallery ? (progress.sample?.record.id === selected?.id ? progress.sample?.checked ?? [] : []) : progress.entries.find(entry => entry.key === preparationKey)?.checked ?? [];
  const canPrepare = Boolean(selected && preparationEligible(selected, selectedBasis));
  const complete = canPrepare && !progress.error && advisoryPreparationItems.every(item => checked.includes(item.id));
  const showReadyConfirmation = complete && completionKey === preparationKey;
  const list = (view: AdvisoryTab, type: AdvisoryFilter = "all") => records.filter(record => advisoryTab(record) === view && (type === "all" || record.details.type === type));
  const visible = list(tab, filter), relevant = list("active").filter(record => ["scheduled", "unscheduled"].includes(record.details.type) && matchPreviewAdvisory(record.details, basis).status === "affected" && !matchIsStale(record, basis)), next = relevant[0];
  useEffect(() => {
    const now = new Date(); setExamples((["scheduled", "uncertain", "not-listed", "restored", "notice"] as AdvisorySample[]).map(kind => { const input = sampleAdvisory(kind, now); return { version: "advisory-ui-v1", id: `sample-gallery-${kind}`, revision: 1, createdAt: now.toISOString(), reviewedAt: now.toISOString(), ...input, match: captureMatch(input.details, sampleMatchHousehold, now) }; }));
    const sync = () => setOffline(!navigator.onLine); sync(); window.addEventListener("online", sync); window.addEventListener("offline", sync); return () => { window.removeEventListener("online", sync); window.removeEventListener("offline", sync); };
  }, []);
  useEffect(() => { if (!ready || queryRead.current || !examples.length) return; queryRead.current = true; const query = new URLSearchParams(window.location.search), id = query.get("reviewed"), sampleId = query.get("sample"); if (id && saved.records.some(record => record.id === id)) { checklistRequested.current = query.get("checklist") === "1"; setSelection({ id, gallery: false }); } else if (sampleId && examples.some(record => record.id === sampleId)) { checklistRequested.current = query.get("checklist") === "1"; setGallery(true); setSelection({ id: sampleId, gallery: true }); } }, [ready, saved.records, examples]);
  useEffect(() => { if (selected && !dialog.current?.open) dialog.current?.showModal(); if (selected && checklistRequested.current) { checklistRequested.current = false; focusUncheckedItem(); } }, [selected]);
  function open(record: ReviewedAdvisory, element: HTMLButtonElement) { trigger.current = element; setDeleting(false); setMessage(""); setCompletionKey(null); setSelection({ id: record.id, gallery }); }
  function focusUncheckedItem() { const input = dialog.current?.querySelector<HTMLInputElement>('.adv-ready input:not(:checked)'); input?.closest('label')?.scrollIntoView({ block: 'center' }); input?.focus({ preventScroll: true }); }
  function togglePreparation(id: AdvisoryPreparationId) {
    setCompletionKey(null);
    if (!selected || !canPrepare) return;
    if (selection?.gallery) progress.toggleSample(selected, id);
    else progress.toggle(selected, selectedBasis, id);
  }
  function finishReview() {
    if (complete) { setCompletionKey(preparationKey); dialog.current?.scrollTo({ top: 0 }); }
    else dialog.current?.close();
  }
  function keyTabs(event: KeyboardEvent<HTMLButtonElement>) { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const target = event.key === "Home" ? "active" : event.key === "End" ? "history" : tab === "active" ? "history" : "active"; setTab(target); tabs.current[target]?.focus(); }
  function confirmMatch() { if (selected && saved.save({ ...selected, match: captureMatch(selected.details, household) })) setMessage("Match reviewed for your current household. Advisory fields and original are unchanged."); }
  const source = selected ? sourceLink(selected.details.sourceUrl) : null;
  return <div className="ws-home adv-page aw-list-page"><div className="ws-shell"><AppHeader title="Advisories" subtitle="Keep the original. Review your area." /><main className="adv-main">
    <div className="adv-intro"><h1>Advisories</h1><p>Keep the original. Review your area.</p></div>
    <div className="aw-list-actions"><Link href="/brownout-ready" className="aw-ready-link"><Save size={15} aria-hidden="true" />Brownout Ready Mode</Link><Link href="/advisories/new" className="ui-primary"><Plus size={17} aria-hidden="true" />Add advisory</Link></div>
    <section className={`adv-hero ${next ? "is-alert" : "is-clear"}`} aria-labelledby="adv-hero-title"><div className="adv-hero-copy">{gallery ? <span className="adv-location"><MapPin aria-hidden="true" /><span>{sampleMatchHousehold.location}</span><em>Sample</em></span> : <Link href="/onboarding" className="adv-location" aria-label="Review household location and provider"><MapPin aria-hidden="true" /><span>{household.location || "Complete household setup"}</span><em>Change</em></Link>}<p className="adv-hero-eyebrow">{gallery ? "Fictional announcement examples" : next ? "Matching saved announcement" : "Saved sources, clearer input basis"}</p><h2 id="adv-hero-title">{gallery ? "Explore advisory examples" : next ? `${relevant.length} saved ${relevant.length === 1 ? "notice matches" : "notices match"} your inputs` : saved.records.length ? "Review your saved advisories" : "Keep provider notices close"}</h2><p className="adv-hero-when">{next ? <><CalendarDays aria-hidden="true" /><span>{dateLabel(next.details.date)} · {scheduleLabel(next.details)}</span></> : "A saved review does not confirm live power status."}</p>{next && <button type="button" className="adv-hero-button" onClick={event => open(next, event.currentTarget)}>Review match<ChevronRight size={16} aria-hidden="true" /></button>}</div><Image className="adv-hero-art" src={next ? "/assets/branding/actions-6.png" : "/assets/branding/actions-3.png"} alt="" width={260} height={260} sizes="(min-width: 900px) 190px, 82px" priority /></section>
    {offline && <div className="aw-note" role="status"><WifiOff aria-hidden="true" /><p><strong>You’re offline.</strong>Saved reviews, originals, and match explanations are available here. No new provider announcements are fetched.</p></div>}
    {!ready && <div className="aw-loading" role="status"><Clock3 aria-hidden="true" />Loading your saved advisories…</div>}
    {saved.error && <p className="ui-error" role="alert">{saved.error}<button type="button" onClick={saved.reload}>Retry loading</button></p>}
    <div className="aw-source-views" role="group" aria-label="Advisory source view"><button type="button" disabled={!ready} aria-pressed={!gallery} onClick={() => { setGallery(false); setFilter("all"); setTab("active"); }}>Saved advisories <span>{saved.records.length}</span></button><button type="button" disabled={!ready} aria-pressed={gallery} onClick={() => { setGallery(true); setFilter("all"); setTab("active"); }}><Sparkles size={14} aria-hidden="true" />Samples</button></div>
    {gallery && <p className="aw-sample-context">Sample design · matches use an example ANTECO household in Payao, San Jose de Buenavista, Antique. They do not describe your current household or a real interruption.</p>}
    <div className="adv-toolbar"><div className="adv-tabs" role="tablist" aria-label="Advisory views">{(["active", "history"] as const).map(value => <button type="button" key={value} ref={element => { tabs.current[value] = element; }} id={`adv-${value}-tab`} role="tab" aria-selected={tab === value} aria-controls="adv-list-panel" tabIndex={tab === value ? 0 : -1} className={tab === value ? "is-selected" : ""} onClick={() => setTab(value)} onKeyDown={keyTabs}>{value === "active" ? <Megaphone aria-hidden="true" /> : <Clock3 aria-hidden="true" />}{value === "active" ? "Active" : "History"}<span className="adv-tab-count">{list(value).length}</span></button>)}</div><div className="adv-filters" role="group" aria-label="Filter advisory type">{filters.map(item => <button type="button" key={item.value} aria-pressed={filter === item.value} className={filter === item.value ? "is-selected" : ""} onClick={() => setFilter(item.value)}>{item.label}<span>{list(tab, item.value).length}</span></button>)}</div></div>
    <section id="adv-list-panel" role="tabpanel" aria-labelledby={`adv-${tab}-tab`} tabIndex={0}><h2 className="adv-list-title">{gallery ? "Sample " : ""}{tab === "active" ? "active advisories" : "advisory history"}</h2><div className="adv-list">{visible.map(record => { const Icon = icons[record.details.type], status = matchPreviewAdvisory(record.details, basis).status, stale = matchIsStale(record, basis); return <article key={record.id} className={`adv-card adv-type-${record.details.type}`}><button type="button" className="adv-card-button" aria-label={`View ${record.details.title || advisoryTypeLabels[record.details.type]}, ${matchLabels[status]}`} onClick={event => open(record, event.currentTarget)}><span className="adv-card-top"><span className="adv-event-mark" aria-hidden="true"><Icon /></span><span className="adv-card-title">{record.details.title || advisoryTypeLabels[record.details.type]}</span><span className={`adv-status adv-status-${status}`}>{matchLabels[status]}</span></span><span className="aw-card-tags">{record.original.kind === "sample" ? <em>Sample</em> : <em>Reviewed locally</em>}{stale && <em className="is-stale">Match needs review</em>}<span>{previewProviderName(record.details.provider)}</span></span><span className="adv-card-body"><span className="adv-date-tile" aria-hidden="true">{record.details.date ? <><small>{record.details.date.slice(0, 7)}</small><b>{Number(record.details.date.slice(-2))}</b><small>Date</small></> : <><b>?</b><small>Unknown</small></>}</span><span className="adv-card-details"><span><Clock3 aria-hidden="true" /><span>{scheduleLabel(record.details)}</span></span><span><MapPin aria-hidden="true" /><span>{record.details.areaText}</span></span><span className="adv-detail-muted"><Wrench aria-hidden="true" /><span>{record.details.reason || "Reason not provided"}</span></span></span></span><span className="adv-card-foot"><span>View original and review</span><ChevronRight aria-hidden="true" /></span></button></article>; })}{ready && !visible.length && <div className="adv-empty"><Image src="/assets/branding/actions-7.png" alt="" width={200} height={200} sizes="110px" /><h3>{!gallery && !saved.records.length ? "No saved advisories yet" : "No advisories in this view"}</h3><p>{!saved.records.length && !gallery ? "Upload a screenshot or paste a provider announcement, then review its details. You can also explore labeled samples." : "Try the other tab or show all advisory types."}</p>{!saved.records.length && !gallery ? <Link href="/advisories/new">Add your first advisory</Link> : <button type="button" onClick={() => setFilter("all")}>Show all types</button>}</div>}</div><span className="ws-sr-only" aria-live="polite">{visible.length} advisories shown</span><p className="adv-source-note"><Info aria-hidden="true" />No automatic collection or AI parsing is connected. Reviewed originals are your reference; check your provider for current updates.</p></section>
  </main><AppNavigation active="Advisories" />
    <dialog ref={dialog} className={`adv-dialog adv-detail aw-detail-dialog${showReadyConfirmation ? " adv-complete" : ""}`} aria-labelledby={showReadyConfirmation ? "adv-ready-title" : "aw-detail-title"} aria-describedby={showReadyConfirmation ? "adv-ready-description" : undefined} onClose={event => { if (event.target !== event.currentTarget) return; setSelection(null); setDeleting(false); setCompletionKey(null); trigger.current?.focus(); }}>
      {selected && (showReadyConfirmation ? <AdvisoryPreparationComplete sample={selected.original.kind === "sample"} onClose={() => dialog.current?.close()} onBack={() => setCompletionKey(null)} /> : <div className="adv-dialog-content" key={selected.id}><div className={`adv-detail-head adv-type-${selected.details.type}`}><button type="button" className="adv-dialog-close" autoFocus aria-label="Close advisory details" onClick={() => dialog.current?.close()}><X /></button><p className="adv-dialog-eyebrow">{selected.original.kind === "sample" ? "Sample advisory · UI preview" : "Saved advisory · reviewed locally"}</p><h2 id="aw-detail-title">{selected.details.title || advisoryTypeLabels[selected.details.type]}</h2><span className="aw-review-stamp">Review {selected.revision} · {timestamp(selected.reviewedAt)} Asia/Manila</span></div><dl className="adv-detail-list"><div><dt><CalendarDays aria-hidden="true" />Date</dt><dd>{dateLabel(selected.details.date)}</dd></div><div><dt><Clock3 aria-hidden="true" />Schedule</dt><dd>{scheduleLabel(selected.details)}</dd></div><div className="adv-detail-wide"><dt><MapPin aria-hidden="true" />Areas as written</dt><dd>{selected.details.areaText}</dd></div><div className="adv-detail-wide"><dt><Wrench aria-hidden="true" />Reason</dt><dd>{selected.details.reason || "Not provided"}</dd></div><div className="adv-detail-wide"><dt>Expected restoration</dt><dd>{selected.details.expectedRestoration || "Unknown · not provided"}</dd></div><div className="adv-detail-wide"><dt>Source attribution</dt><dd>{selected.details.publisher || "Publisher not provided"} · {previewProviderName(selected.details.provider)}{source && <a href={source} target="_blank" rel="noreferrer">Open source link</a>}</dd></div></dl>
      {selected.details.type === "restored" && <div className="aw-note"><Info aria-hidden="true" /><p><strong>Separate restoration update</strong>{selected.details.relatedId ? `Linked earlier advisory: ${saved.records.find(record => record.id === selected.details.relatedId)?.details.title || "earlier saved advisory"}. Its original has not been replaced.` : "No earlier advisory has been linked. This update does not replace another announcement."}</p></div>}
      <LocationMatchPreview details={selected.details} household={selectedBasis} record={selected} sampleBasis={Boolean(selection?.gallery)} onRecheck={selection?.gallery ? undefined : confirmMatch} disabled={!ready} />
      {canPrepare && <AdvisoryPreparationChecklist checked={checked} disabled={!ready || progress.loadError} sample={selected.original.kind === "sample"} onToggle={togglePreparation} />}
      {progress.error && <p id="adv-progress-error" className="ui-error" role="alert" tabIndex={-1}>{progress.error}<button type="button" onClick={progress.reload}>Retry loading checklist</button></p>}
      <AdvisoryOriginalView original={selected.original} /><p className="aw-muted">Original retained {timestamp(selected.original.capturedAt)} Asia/Manila. A saved schedule is not a live outage or restoration confirmation.</p>
      {message && <p className="ui-success" role="status">{message}</p>}{saved.error && <p className="ui-error" role="alert">{saved.error}</p>}
      <div className="aw-detail-actions"><div className="aw-detail-links">{selection?.gallery ? <Link className="ui-primary" href={`/advisories/new?sample=${selected.original.sample}`} onClick={() => dialog.current?.close()}>Try this sample review</Link> : <><Link className="ui-secondary" href={`/advisories/new?edit=${selected.id}`} onClick={() => dialog.current?.close()}><Save size={16} aria-hidden="true" />Correct review fields</Link>{["scheduled", "unscheduled"].includes(selected.details.type) && <Link className="ui-primary" href={`/brownout-ready?advisory=${encodeURIComponent(selected.id)}`} onClick={() => dialog.current?.close()}>Prepare with this advisory</Link>}</>}</div><div className="aw-detail-buttons"><button type="button" className="ui-secondary" onClick={() => dialog.current?.close()}>Close</button><button type="button" className="ui-primary" onClick={finishReview}>Done</button></div></div>
      {!selection?.gallery && <details className="aw-manage"><summary>Manage saved advisory</summary>{deleting ? <div><p>Remove this review and its locally saved original? Other advisories will stay available.</p><button type="button" onClick={() => { if (saved.remove(selected.id)) dialog.current?.close(); }}>Remove advisory and original</button><button type="button" onClick={() => setDeleting(false)}>Keep advisory</button></div> : <button type="button" onClick={() => setDeleting(true)}>Remove saved advisory</button>}</details>}
      </div>)}
    </dialog>
  </div></div>;
}
