"use client";
import { useState, type FormEvent } from "react";
import { Plus, Save, Trash2, TriangleAlert } from "lucide-react";
import { previewProviders } from "@/features/household-profile/provider-preview";
import type { PreviewHousehold } from "@/features/dashboard/preview-data";
import { advisoryTypeLabels } from "../advisory-preview";
import { advisoryInputWarnings, blankArea, originalIsDuplicate, validateAdvisory } from "../review-preview";
import type { AdvisoryDetails, AdvisoryOriginal, ReviewedAdvisory } from "../types";
import AdvisoryOriginalView from "./advisory-original";
import LocationMatchPreview from "./location-match-preview";

export default function AdvisoryReview({ initial, original, household, records, editingId, ready, storageError, onSave, onRestart, onRetryLoading }: { initial: AdvisoryDetails; original: AdvisoryOriginal; household: PreviewHousehold; records: ReviewedAdvisory[]; editingId?: string; ready: boolean; storageError: string; onSave: (details: AdvisoryDetails) => void; onRestart: () => void; onRetryLoading?: () => void }) {
  const [draft, setDraft] = useState(initial), [reviewed, setReviewed] = useState(false), [allowDuplicate, setAllowDuplicate] = useState(false), [error, setError] = useState("");
  const [keepPhoto, setKeepPhoto] = useState(Boolean(editingId && original.kind === "image"));
  const customProvider = draft.provider.startsWith("custom:");
  const warnings = advisoryInputWarnings(draft), duplicate = originalIsDuplicate(original, records, editingId);
  function change(patch: Partial<AdvisoryDetails>) { setDraft(current => ({ ...current, ...patch })); setReviewed(false); setAllowDuplicate(false); setError(""); }
  function area(index: number, patch: Partial<AdvisoryDetails["areas"][number]>) { change({ areas: draft.areas.map((item, i) => i === index ? { ...item, ...patch } : item) }); }
  function submit(event: FormEvent) {
    event.preventDefault();
    const details = { ...draft, title: draft.title.trim(), publisher: draft.publisher.trim(), sourceUrl: draft.sourceUrl.trim(), areaText: draft.areaText.trim(), reason: draft.reason.trim(), expectedRestoration: draft.expectedRestoration.trim(), areas: draft.areas.map(item => ({ ...item, province: item.province.trim(), municipality: item.municipality.trim(), barangay: item.barangay.trim() })) };
    const invalid = validateAdvisory(details);
    if (invalid) { setError(invalid); return; }
    if (original.kind === "image" && !keepPhoto) { setError("Choose to keep this original screenshot on this device before saving its review, or use pasted text instead."); return; }
    if (!reviewed) { setError("Confirm that you reviewed the original and these fields before saving."); return; }
    if (duplicate && !allowDuplicate) { setError("This original is already saved. Confirm saving a separate review, or return to the existing advisory."); return; }
    setError(""); onSave(details);
  }
  return <>
    <div className="aw-review-intro"><h2>{editingId ? "Correct your saved review" : "Review advisory details"}</h2><p>{original.kind === "sample" ? "Sample values are prefilled for this design. Check every field; this is not a current announcement." : "Nothing was extracted automatically. Copy the original details below and leave absent or ambiguous values unknown."}</p></div>
    {original.kind === "sample" && <p className="aw-sample-badge">Sample advisory · UI preview</p>}
    <AdvisoryOriginalView original={original} />
    <form noValidate onSubmit={submit} className="aw-review-form"><section className="ui-panel aw-fields"><h2>Announcement and source</h2><div className="aw-field-grid"><label>Advisory type<select value={draft.type} onChange={event => change({ type: event.target.value as AdvisoryDetails["type"], relatedId: event.target.value === "restored" ? draft.relatedId : "" })}>{Object.entries(advisoryTypeLabels).map(([value, label]) => <option key={value} value={value}>{value === "restored" ? "Restoration update" : label}</option>)}</select></label><label>Review title (optional)<input value={draft.title} maxLength={300} onChange={event => change({ title: event.target.value })} placeholder="A short label for your saved review" /></label><label>Provider named in the advisory<select value={customProvider ? "other" : draft.provider} onChange={event => change({ provider: event.target.value === "other" ? household.provider?.startsWith("custom:") ? household.provider : "custom:" : event.target.value })}><option value="">Unknown / not provided</option>{previewProviders.map(provider => <option key={provider.id} value={provider.id}>{provider.name}</option>)}<option value="other">Other provider</option></select></label>{customProvider && <label>Provider name<input maxLength={80} value={decodeURIComponent(draft.provider.slice(7))} onChange={event => change({ provider: `custom:${encodeURIComponent(event.target.value)}` })} /></label>}<label>Publisher / source name<input value={draft.publisher} maxLength={300} onChange={event => change({ publisher: event.target.value })} placeholder="Copy the publisher as shown" /></label><label className="aw-wide">Original source link (optional)<input type="url" value={draft.sourceUrl} maxLength={300} onChange={event => change({ sourceUrl: event.target.value })} placeholder="https://…" /></label></div><p className="aw-muted">Choosing a provider records your interpretation. It does not verify the publisher or the upload.</p></section>
      <section className="ui-panel aw-fields"><h2>Published schedule</h2><p>All entered schedule times use Asia/Manila (UTC+08:00). Keep anything absent or uncertain blank.</p><div className="aw-field-grid"><label>Interruption date<input type="date" value={draft.date} onChange={event => change({ date: event.target.value })} /></label><label>Start time<input type="time" value={draft.startTime} onChange={event => change({ startTime: event.target.value })} /></label><label>End date (if different)<input type="date" value={draft.endDate} onChange={event => change({ endDate: event.target.value })} /><small>Leave blank when a known end time is on the interruption date.</small></label><label>End time<input type="time" value={draft.endTime} onChange={event => change({ endTime: event.target.value })} /></label><label className="aw-wide">Expected restoration as stated (optional)<input value={draft.expectedRestoration} maxLength={300} onChange={event => change({ expectedRestoration: event.target.value })} placeholder="Leave blank if the original does not state it" /></label><label className="aw-wide">Reason as stated (optional)<textarea rows={2} value={draft.reason} maxLength={1500} onChange={event => change({ reason: event.target.value })} /></label></div></section>
      <section className="ui-panel aw-fields aw-area-fields"><h2>Affected-area wording</h2><label>Areas as written in the original<textarea rows={3} value={draft.areaText} maxLength={1500} onChange={event => change({ areaText: event.target.value })} placeholder="Copy the wording; write Not provided if it is absent" /></label><p>Enter separate locality rows where the original identifies them. Select an exact scope only when the whole named barangay or municipality is clearly included.</p>{draft.areas.map((item, index) => <fieldset key={index} className="aw-area"><legend>Area {index + 1}</legend><div className="aw-field-grid"><label>Province<input aria-label={`Province for area ${index + 1}`} value={item.province} maxLength={100} onChange={event => area(index, { province: event.target.value })} /></label><label>Municipality / city<input aria-label={`Municipality for area ${index + 1}`} value={item.municipality} maxLength={100} onChange={event => area(index, { municipality: event.target.value })} /></label><label>Barangay<input aria-label={`Barangay for area ${index + 1}`} value={item.barangay} maxLength={100} disabled={item.scope === "municipality"} onChange={event => area(index, { barangay: event.target.value })} /></label><label>Listed area scope<select aria-label={`Scope for area ${index + 1}`} value={item.scope} onChange={event => area(index, { scope: event.target.value as typeof item.scope, ...(event.target.value === "municipality" ? { barangay: "" } : {}) })}><option value="uncertain">Uncertain or partial area</option><option value="barangay">Whole named barangay</option><option value="municipality">Whole named municipality</option></select></label></div><button type="button" className="aw-remove-area" aria-label={`Remove area ${index + 1}`} onClick={() => change({ areas: draft.areas.filter((_, i) => i !== index) })}><Trash2 size={14} aria-hidden="true" />Remove area</button></fieldset>)}<button type="button" className="ui-secondary" disabled={draft.areas.length >= 20} onClick={() => change({ areas: [...draft.areas, { ...blankArea }] })}><Plus size={16} aria-hidden="true" />Add another area</button></section>
      {draft.type === "restored" && <section className="ui-panel aw-fields"><h2>Link this restoration update</h2><p>Save this as its own update. An earlier announcement and its original will remain available.</p><label>Earlier advisory (optional)<select value={draft.relatedId} onChange={event => change({ relatedId: event.target.value })}><option value="">Not identified / no link</option>{records.filter(record => record.id !== editingId && ["scheduled", "unscheduled"].includes(record.details.type)).map(record => <option key={record.id} value={record.id}>{record.details.title || advisoryTypeLabels[record.details.type]} · {record.details.date || "Date unknown"}{record.original.kind === "sample" ? " · Sample" : ""}</option>)}</select></label></section>}
      <LocationMatchPreview details={draft} household={household} />
      {!!warnings.length && <section className="aw-warnings" aria-label="Missing or uncertain details"><h2><TriangleAlert size={17} aria-hidden="true" />Review these limits</h2><ul>{warnings.map(warning => <li key={warning}>{warning}</li>)}</ul></section>}
      <section className="ui-panel aw-confirm"><h2>Confirm your review</h2>{original.kind === "image" && <label><input type="checkbox" checked={keepPhoto} onChange={event => { setKeepPhoto(event.target.checked); setError(""); }} /><span>Keep the original screenshot with this saved review on this device. Anyone using this browser can view it.</span></label>}<label><input type="checkbox" checked={reviewed} onChange={event => { setReviewed(event.target.checked); setError(""); }} /><span>I checked the original and these fields, and kept missing or uncertain values unknown.</span></label><p className="aw-muted">Review confirmation is not independent source verification. Changing a field resets it.</p>{duplicate && <div className="aw-duplicate"><p>This original already has a saved review: <strong>{duplicate.details.title || advisoryTypeLabels[duplicate.details.type]}</strong>.</p><label><input type="checkbox" checked={allowDuplicate} onChange={event => { setAllowDuplicate(event.target.checked); setError(""); }} /><span>Save another review of this original as a separate advisory.</span></label></div>}{(error || storageError) && <p className="ui-error" role="alert">{error || storageError}{onRetryLoading && <button type="button" onClick={onRetryLoading}>Retry loading saved advisories</button>}</p>}<div className="aw-save-actions"><button type="submit" className="ui-primary" disabled={!ready}><Save size={17} aria-hidden="true" />{editingId ? "Save corrected review" : "Save reviewed advisory"}</button><button type="button" className="ui-secondary" onClick={onRestart}>{editingId ? "Cancel correction" : "Choose another original"}</button></div></section>
    </form>
  </>;
}
